services:
  nginx:
    ports:
      - "8000:80"


  reverb:
    ports:
      - "8080:8080"


  mysql:
    ports:
      - "3307:3306"


  redis:
    ports:
      - "6380:6379"


  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - shelfspot


  node:
    image: node:22-alpine
    user: "${UID:-1000}:${GID:-1000}"
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
